- python  
   - python is a programming paradism means it supports functional  programming and object oriented programming and also works with procedure oriented programming  
- procedure oriented language  
   - procedure oriented means write our programming language using functions and objects and classes  
- Object oriented language  
   - object:real word entity or it is a physical entity represented memory  
   - class:logical entity contains logic of the application  

In [ ]:
# syntax for class::
class class_name:
    variables
    methods or funtion

In [7]:
print("hi hello")

hi hello


In [8]:
8+9

17

In [10]:
class Hi:
    a=10
    b=30
    name="apssdc"
    def show():
        print("i am from show() function")

In [11]:
Hi.name

'apssdc'

In [12]:
Hi.a

10

In [13]:
Hi.b

30

In [14]:
Hi.show()

i am from show() function


In [15]:
print(Hi.a,Hi.b)

10 30


In [20]:
class Hi:
    name="apssdc"
    program_name='python'
    def display():
        print("i am from display function")
    def show():
        print("i am from show function")
print(Hi.name,Hi.program_name)
print(Hi.display())

apssdc python
i am from display function
None


In [21]:
print(Hi.display())

i am from display function
None


In [25]:
class Hello():
    def display():
        print("i am from display function")
        return("i am from return statement")
    def show():
        print("i am from show function")
print(Hello.display())
print(Hello.show())

i am from display function
i am from return statement
i am from show function
None


In [26]:
# In Java obj declaration:
   # class_name obj_name=new_classname
# In python  
   # obj_name=class_name

In [27]:
class Hi:
    name="apssdc"
    program_name='python'
    def display(self):
        print("i am from display function")
        return("i am from return statement")
    def show():
        print("i am from show function")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

apssdc python
i am from display function
i am from return statement


### Constructor  
- Constructor:without using object we will call methods  
   - in java::class name should be same as method name  
   - i python::we will use one special method to define constructor  
   - __init(self)__

In [28]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def display(self):  
        print("your roll_no",self.roll_no)
obj=Hai('santosh','21A85A0510')
obj.display()

hi santosh
your roll_no 21A85A0510


### Inheritance  
- inherits something from parent class to child class

In [ ]:
class A:
    # a,b=10,20
class B(A):
    # c,d=40,50

In [29]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

40 10
i am from class B
i am from class A


### Python libraries for data science  
- organizing,processing,analyzing the huge amount data 
- apply data visualization  
- extracting the data from the source  
- nearly 20 python libraries are there  

### Top  
- Numpy  
- Pandas  
- Matplotlib  

### Numpy  
- Numpy::(num+py) means numerical data+python  
- it is fundamental package for scienticfic computing in python  
- numpy is python library  
- it is used to create multidimensional arrays for fast operations  
   - its dealing with mathematical,scientific,statical data  
   - numpy contains a powerful n-dimensional array object.which in the form of row and columns 
   - we can initialize numpy arrays from nested python lists  

In [31]:
# how to install numpy  
- pip install numpy

SyntaxError: invalid syntax (Temp/ipykernel_4692/1542393256.py, line 2)

In [32]:
# how to import and use numpy package 
import numpy as np  

In [33]:
# how to find the numpy version 
np.__version__

'1.20.3'

In [4]:
# how to create numpy arrays  
import numpy as np  
a=np.array([1,2,3,4]) # single dimensional number  
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
a2=np.array([[2,3,4],[5,6,8]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 8]]
<class 'numpy.ndarray'>


In [6]:
# to know about the shape of the array 
a2.shape

(2, 3)

In [7]:
li=[2,3,4,'hi','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'hi' 'i']
<class 'numpy.ndarray'>


In [8]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
print(ar.dtype)

int32


In [11]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [12]:
print(b.shape)

(2, 2)


In [13]:
b.itemsize

4

In [14]:
b.ndim

2

In [15]:
# range  
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [17]:
# arrange method()-third party of numpy library
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [19]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
# reshape of array 
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [21]:
# resize of array(its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3) # resize the no elements form original array
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [2]:
# zero array
import numpy as np  
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [3]:
# one array  
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [4]:
# full array- full(dimensions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [5]:
np.diag(a)

array([7, 7, 7])

In [6]:
np.full((3,6),500)

array([[500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500]])

In [7]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [9]:
r=np.random.randint(1,10)
r

7

In [10]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 8, 17,  6,  1],
       [17,  3, 10,  4],
       [ 4, 15,  8,  5]])

In [11]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.60171617, 0.71974419, 0.78447985],
       [0.33754795, 0.17968231, 0.12459761]])

In [12]:
f=np.random.randn(2,3)
f

array([[ 0.03644975, -0.48765744, -0.05110014],
       [ 0.86183391,  0.55715515,  0.77423366]])

In [13]:
a=np.random.randint(1,30,(10,3))
a

array([[ 5,  2, 27],
       [16, 28,  6],
       [11, 12, 18],
       [21, 27, 16],
       [ 5, 22, 14],
       [14, 14, 20],
       [11,  5,  2],
       [27,  8, 14],
       [ 3,  1, 23],
       [21, 27, 25]])

In [14]:
a[1:5]

array([[16, 28,  6],
       [11, 12, 18],
       [21, 27, 16],
       [ 5, 22, 14]])

In [15]:
a[2:,:2]

array([[11, 12],
       [21, 27],
       [ 5, 22],
       [14, 14],
       [11,  5],
       [27,  8],
       [ 3,  1],
       [21, 27]])

In [16]:
a

array([[ 5,  2, 27],
       [16, 28,  6],
       [11, 12, 18],
       [21, 27, 16],
       [ 5, 22, 14],
       [14, 14, 20],
       [11,  5,  2],
       [27,  8, 14],
       [ 3,  1, 23],
       [21, 27, 25]])

In [17]:
a>10

array([[False, False,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [18]:
a[a>10]

array([27, 16, 28, 11, 12, 18, 21, 27, 16, 22, 14, 14, 14, 20, 11, 27, 14,
       23, 21, 27, 25])

In [19]:
a[a>10].sum()

408

In [20]:
a.max()

28

In [21]:
a.min()

1

In [22]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [24]:
print(a+b)
print("*******")
print(a-b)
print("_______")
print(a*b)
print("$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))                            

[[10 12 14]
 [16 18 20]
 [22 24 26]]
*******
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
_______
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [25]:
# 0 to 15 --->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [26]:
print(np.mean(a))

7.0


In [27]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [28]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
np.log2(2)

1.0

In [30]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [31]:
np.exp(1)

2.718281828459045

In [32]:
np.sin(30)

-0.9880316240928618

In [33]:
np.cos(30)

0.15425144988758405

In [34]:
np.tan(30)

-6.405331196646276

### Pandas  
- pandas is the datascience package
- It is used for 
   - Data manipulation(modifications and updations)
   - Data Analysis
   - Data cleaning(to remove unnecessery data from data sets) 
- contains mainly two data structures in pandas  
   - Series---Sequence of a data  
   - Data Frames---Data with row and column  